#pragma once

// ------------------------------------------------------------------------------------------------
namespace lmcu::isr {
// ------------------------------------------------------------------------------------------------

void default_handler();
void nmi();
void hard_fault();
void mem_manage();
void bus_fault();
void usage_fault();
void svcall();
void debug_mon();
void pend_sv();
void sys_tick();

void bod();
void irc();
void pwrwu();
void rampe();
void ckfail();
void rtc();
void tamper();
void wdt();
void wwdt();
void eint0();
void eint1();
void eint2();
void eint3();
void eint4();
void eint5();
void gpa();
void gpb();
void gpc();
void gpd();
void gpe();
void gpf();
void qspi0();
void spi0();
void brake0();
void epwm0p0();
void epwm0p1();
void epwm0p2();
void brake1();
void epwm1p0();
void epwm1p1();
void epwm1p2();
void timer0();
void timer1();
void timer2();
void timer3();
void uart0();
void uart1();
void i2c0();
void i2c1();
void pdma();
void dac();
void eadc00();
void eadc01();
void acmp();
void eadc02();
void eadc03();
void uart2();
void uart3();
void qspi1();
void spi1();
void spi2();
void usbd();
void ohci();
void otg();
void can0();
void can1();
void sc0();
void sc1();
void sc2();
void spi3();
void sdh0();
void hsusbd();
void emac_tx();
void emac_rx();
void i2s();
void opa();
void crypto();
void gpg();
void eint6();
void uart4();
void uart5();
void usci0();
void usci1();
void bpwm0();
void bpwm1();
void spim();
void ccap();
void i2c2();
void qei0();
void qei1();
void ecap0();
void ecap1();
void gph();
void eint7();
void sdh1();
void ehci();
void hsotg();
void trng();
void uart6();
void uart7();
void eadc10();
void eadc11();
void eadc12();
void eadc13();
void can2();

// ------------------------------------------------------------------------------------------------
} // namespace lmcu::isr
// ------------------------------------------------------------------------------------------------
